"""empty message

Revision ID: c2b5ab95a874
Revises: 
Create Date: 2020-03-31 19:50:28.370385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b5ab95a874'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.drop_column('options', 'option_id')
    op.drop_column('options', 'vote_count')
    op.drop_column('options', 'topic_id')
    op.drop_column('options', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('status', sa.BOOLEAN(), nullable=True))
    op.add_column('options', sa.Column('topic_id', sa.INTEGER(), nullable=True))
    op.add_column('options', sa.Column('vote_count', sa.INTEGER(), nullable=True))
    op.add_column('options', sa.Column('option_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'options', 'topics', ['topic_id'], ['id'])
    op.create_foreign_key(None, 'options', 'options', ['option_id'], ['id'])
    # ### end Alembic commands ###
